theme: jekyll-theme-slate
show_downloads: true
github:
  zip_url: https://github.com/WillyTrek19/Project-19-2000/releases/download/v0.8/Bruhmentium_Inc.-Shattered_Dreams_v1.0.zip
  tar_url: https://github.com/WillyTrek19/Project-19-2000/releases/download/v0.8/Bruhmentium_Inc.-Shattered_Dreams_v1.0.zip
